// Seed data ported from the original static front-end catalog.
// `image_key` / `gallery_keys` map to bundled assets on the front-end
// (see Frontend/src/lib/assetMap.js). Prices are stored in cents.

export const collectionsSeed = [
  {
    id: 'original',
    name: 'Original',
    slug: 'original',
    blurb: 'Honest smoke, clean spice. Where every flavor journey begins.',
    image_key: 'originalBuffalo',
    accent: 'ember',
    sort_order: 1,
  },
  {
    id: 'teriyaki',
    name: 'Teriyaki',
    slug: 'teriyaki',
    blurb: 'Pineapple and cane sugar glaze over lean mountain game.',
    image_key: 'teriyakiElk',
    accent: 'teal',
    sort_order: 2,
  },
  {
    id: 'sweet-peppered',
    name: 'Sweet Peppered',
    slug: 'sweet-peppered',
    blurb: 'Brown-sugar sweetness met with a confident crack of pepper.',
    image_key: 'sweetPepperedElk',
    accent: 'ember',
    sort_order: 3,
  },
  {
    id: 'hot',
    name: 'Hot',
    slug: 'hot',
    blurb: 'A slow-building heat for those who like it bold.',
    image_key: 'teriyakiBuffalo',
    accent: 'ember',
    sort_order: 4,
  },
  {
    id: 'sweet-and-hot',
    name: 'Sweet & Hot',
    slug: 'sweet-and-hot',
    blurb: 'The push-and-pull of sweet glaze and lingering fire.',
    image_key: 'sweetPepperedVenison',
    accent: 'teal',
    sort_order: 5,
  },
  {
    id: 'peppered',
    name: 'Peppered',
    slug: 'peppered',
    blurb: 'Cracked black pepper, front and center. Pure and bold.',
    image_key: 'lifestyleBoard',
    accent: 'teal',
    sort_order: 6,
  },
];

export const productsSeed = [
  {
    id: 'original-buffalo',
    slug: 'original-buffalo-jerky',
    name: '3.2 oz. Original Buffalo Jerky',
    short_name: 'Original Buffalo',
    flavor: 'Original',
    meat: 'Buffalo',
    price_cents: 1300,
    weight: '3.2 oz (92g)',
    image_key: 'originalBuffalo',
    gallery_keys: ['originalBuffalo', 'lifestyleBoard'],
    rating: 4.9,
    review_count: 128,
    badge: 'Best Seller',
    best_seller: true,
    tagline: 'Lean bison. Honest smoke.',
    description: [
      'Our Original Buffalo Jerky is the cleanest expression of what we do — premium bison seasoned with a simple spice blend and finished with honest, slow smoke.',
      'Crafted in Springville, Utah in small batches, it delivers lean protein with a deep, grounded flavor that never overpowers the meat.',
      'Bold without the noise. This is the jerky we hand to anyone asking where to start.',
    ],
    flavor_notes: ['Smoky', 'Savory', 'Clean Finish'],
    ingredients:
      'Buffalo, Spice Mix / Sea Salt, Dextrose, Corn Syrup Solids, Maltodextrin, Spices, Canola Oil, Vinegar, Brown Sugar, Smoke Flavoring, Salt, Garlic Powder.',
    allergens: 'Made in a facility that processes soy and wheat.',
    nutrition: { calories: 130, protein: '12g', fat: '5g', sodium: '480mg' },
    pairs: ['teriyaki-buffalo', 'sweet-peppered-elk'],
    sort_order: 1,
  },
  {
    id: 'original-venison',
    slug: 'original-venison-jerky',
    name: '3.2 oz. Original Venison Jerky',
    short_name: 'Original Venison',
    flavor: 'Original',
    meat: 'Venison',
    price_cents: 1500,
    weight: '3.2 oz (92g)',
    image_key: 'sweetPepperedVenison',
    gallery_keys: ['sweetPepperedVenison', 'lifestyleBoard'],
    rating: 5.0,
    review_count: 96,
    badge: 'Small Batch',
    best_seller: true,
    tagline: 'Wild game done right.',
    description: [
      'Our Original Venison Jerky captures the rich, earthy depth of premium deer meat in a clean, balanced profile. Crafted in Springville, Utah in small batches, this jerky delivers lean protein with distinctive character.',
      'Venison offers a robust flavor that stands apart from beef or bison. We season it intentionally — enhancing its natural richness without masking it.',
      'The result is bold, refined wild game jerky made for those who want something real in their pack.',
    ],
    flavor_notes: ['Earthy', 'Robust', 'Lean'],
    ingredients:
      'Venison, Sea Salt, Spices, Vinegar, Brown Sugar, Smoke Flavoring, Garlic Powder, Natural Flavor.',
    allergens: 'Made in a facility that processes soy and wheat.',
    nutrition: { calories: 90, protein: '13g', fat: '2g', sodium: '430mg' },
    pairs: ['sweet-peppered-venison', 'teriyaki-venison'],
    sort_order: 2,
  },
  {
    id: 'sweet-peppered-elk',
    slug: 'sweet-peppered-elk-jerky',
    name: '3.2 oz. Sweet Peppered Elk Jerky',
    short_name: 'Sweet Peppered Elk',
    flavor: 'Sweet Peppered',
    meat: 'Elk',
    price_cents: 1500,
    weight: '3.2 oz (92g)',
    image_key: 'sweetPepperedElk',
    gallery_keys: ['sweetPepperedElk', 'lifestyleBoard'],
    rating: 4.8,
    review_count: 84,
    badge: 'Fan Favorite',
    best_seller: true,
    tagline: 'Sweet heat, mountain elk.',
    description: [
      'Sweet Peppered Elk balances brown-sugar sweetness against a confident crack of black pepper, all carried by lean, premium elk.',
      'Smoke flavor is added the right way — for depth, not disguise — so every bite stays tender with a satisfying chew.',
      'It is the flavor people reach for again and again. A little sweet, a little bold, and unmistakably uncommon.',
    ],
    flavor_notes: ['Sweet', 'Peppered', 'Smoky'],
    ingredients:
      'Elk, Brown Sugar, Vinegar, Salt, Smoke Flavoring, Worcestershire Sauce, Molasses, Hydrolyzed Soy Protein, Caramel Color, Natural Flavor, Spices, Garlic Powder. Contains Soy & Wheat.',
    allergens: 'Contains Soy & Wheat.',
    nutrition: { calories: 50, protein: '8g', fat: '1g', sodium: '410mg' },
    pairs: ['sweet-peppered-venison', 'teriyaki-elk'],
    sort_order: 3,
  },
  {
    id: 'sweet-peppered-venison',
    slug: 'sweet-peppered-venison-jerky',
    name: '3.2 oz. Sweet Peppered Venison Jerky',
    short_name: 'Sweet Peppered Venison',
    flavor: 'Sweet Peppered',
    meat: 'Venison',
    price_cents: 1300,
    weight: '3.2 oz (92g)',
    image_key: 'sweetPepperedVenison',
    gallery_keys: ['sweetPepperedVenison', 'lifestyleBoard'],
    rating: 4.9,
    review_count: 71,
    badge: null,
    best_seller: true,
    tagline: 'Wild game, warm spice.',
    description: [
      'Sweet Peppered Venison layers warm brown sugar over the earthy depth of premium deer meat, finished with a bright peppered edge.',
      'Each batch is built to keep venison tender while letting its natural richness shine through the sweetness.',
      'A campfire favorite — bold enough to share, balanced enough to keep all to yourself.',
    ],
    flavor_notes: ['Sweet', 'Earthy', 'Peppered'],
    ingredients:
      'Venison, Brown Sugar, Vinegar, Salt, Smoke Flavoring, Worcestershire Sauce, Molasses, Hydrolyzed Soy Protein, Caramel Color, Natural Flavor, Spices, Garlic Powder. Contains Soy & Wheat.',
    allergens: 'Contains Soy & Wheat.',
    nutrition: { calories: 50, protein: '9g', fat: '1g', sodium: '400mg' },
    pairs: ['original-venison', 'sweet-peppered-elk'],
    sort_order: 4,
  },
  {
    id: 'teriyaki-elk',
    slug: 'teriyaki-elk-jerky',
    name: '3.2 oz. Teriyaki Elk Jerky',
    short_name: 'Teriyaki Elk',
    flavor: 'Teriyaki',
    meat: 'Elk',
    price_cents: 1500,
    weight: '3.2 oz (92g)',
    image_key: 'teriyakiElk',
    gallery_keys: ['teriyakiElk', 'lifestyleBoard'],
    rating: 4.7,
    review_count: 63,
    badge: null,
    best_seller: false,
    tagline: 'Island sweet meets the mountains.',
    description: [
      'Teriyaki Elk marries lean mountain elk with a house teriyaki built on pineapple juice and brown cane sugar for a glossy, savory-sweet finish.',
      'It is tender, deeply marinated, and balanced — never cloying.',
      'A crowd-pleaser that disappears fast on road trips and game days alike.',
    ],
    flavor_notes: ['Savory-Sweet', 'Umami', 'Tender'],
    ingredients:
      'Elk, Brown Cane Sugar, Pineapple Juice, Ascorbic Acid, Vitamin E, Soy Sauce, Hydrolyzed Soy Protein, Molasses, Caramel Color, Water, Salt, Smoke Flavoring, Natural Flavor, Spices. Contains Soy.',
    allergens: 'Contains Soy.',
    nutrition: { calories: 60, protein: '8g', fat: '1g', sodium: '520mg' },
    pairs: ['teriyaki-venison', 'teriyaki-buffalo'],
    sort_order: 5,
  },
  {
    id: 'teriyaki-venison',
    slug: 'teriyaki-venison-jerky',
    name: '3.2 oz. Teriyaki Venison Jerky',
    short_name: 'Teriyaki Venison',
    flavor: 'Teriyaki',
    meat: 'Venison',
    price_cents: 1300,
    weight: '3.2 oz (92g)',
    image_key: 'teriyakiVenison',
    gallery_keys: ['teriyakiVenison', 'lifestyleBoard'],
    rating: 4.9,
    review_count: 102,
    badge: 'Highly Rated',
    best_seller: true,
    tagline: 'Balanced. Tender. Honest.',
    description: [
      'The teriyaki adds just enough sweetness without overpowering the venison, and the texture stays tender without being soft.',
      'This is the kind of jerky you bring on a long hike or share around a campfire — not gas-station filler.',
      'Premium deer meat, our house teriyaki, and a whole lot of intention.',
    ],
    flavor_notes: ['Savory-Sweet', 'Earthy', 'Tender'],
    ingredients:
      'Venison, Brown Cane Sugar, Pineapple Juice, Ascorbic Acid, Vitamin E, Soy Sauce, Hydrolyzed Soy Protein, Molasses, Caramel Color, Water, Salt, Smoke Flavoring, Natural Flavor, Spices. Contains Soy.',
    allergens: 'Contains Soy.',
    nutrition: { calories: 60, protein: '9g', fat: '1g', sodium: '500mg' },
    pairs: ['teriyaki-elk', 'original-venison'],
    sort_order: 6,
  },
  {
    id: 'teriyaki-buffalo',
    slug: 'teriyaki-buffalo-jerky',
    name: '3.2 oz. Teriyaki Buffalo Jerky',
    short_name: 'Teriyaki Buffalo',
    flavor: 'Teriyaki',
    meat: 'Buffalo',
    price_cents: 1500,
    weight: '3.2 oz (92g)',
    image_key: 'teriyakiBuffalo',
    gallery_keys: ['teriyakiBuffalo', 'lifestyleBoard'],
    rating: 4.8,
    review_count: 58,
    badge: null,
    best_seller: false,
    tagline: 'Lean bison, glossy glaze.',
    description: [
      'Teriyaki Buffalo brings lean bison into our signature pineapple-and-cane-sugar teriyaki for a rich, savory-sweet bite.',
      'Bison keeps it lean and clean while the marinade adds depth and a satisfying glaze.',
      'A standout for anyone who loves teriyaki but wants something leaner than beef.',
    ],
    flavor_notes: ['Savory-Sweet', 'Lean', 'Glazed'],
    ingredients:
      'Buffalo, Brown Cane Sugar, Pineapple Juice, Ascorbic Acid, Vitamin E, Soy Sauce, Hydrolyzed Soy Protein, Molasses, Caramel Color, Water, Salt, Smoke Flavoring, Natural Flavor, Spices. Contains Soy.',
    allergens: 'Contains Soy.',
    nutrition: { calories: 60, protein: '11g', fat: '2g', sodium: '510mg' },
    pairs: ['original-buffalo', 'teriyaki-elk'],
    sort_order: 7,
  },
];
